### ISSUE TITLE
new employee ekranında hata

### ISSUE THREAD

**Issue by aycegsltk** [mesat/os-erp-project#1]
Frontend new employee ekranında sayfa düzenini küçülttüğümüzde sağdaki resim "date" kısmının altına yerleşiyor. Sabit bir şekilde sağ üst köşede kalmıyor.

![image](https://user-images.githubusercontent.com/74659714/127844739-aaf2ffd2-66c7-491a-aafe-4284db672eab.png)

**Comment by alperen-bircak** [comment]
halloldu
